### ISSUE TITLE
Internal Server Error on Ubuntu 16.04 LXC 2.0.0.rc6

### ISSUE THREAD

**Issue by naisanza** [lxc-webpanel/LXC-Web-Panel#98]
LWP has a hardcoded path for LXC templates at `/usr/lib/lxc/templates`

But the location of the LXC directory is in: `/usr/share/lxc`

```
FileNotFoundError: [Errno 2] No such file or directory: '/usr/lib/lxc/templates'
```

```
root@lxc:~# whereis lxc
lxc: /usr/bin/lxc /etc/lxc /usr/share/lxc /usr/share/man/man1/lxc.1.gz /usr/share/man/man7/lxc.7.gz
root@lxc:~# ls /usr/share/lxc
config  hooks  lxc.functions  lxc-patch.py  selinux  templates
root@lxc:~# ls /usr/share/lxc/templates/
lxc-alpine    lxc-archlinux  lxc-centos  lxc-debian    lxc-fedora  lxc-openmandriva  lxc-oracle  lxc-slackware   lxc-sshd    lxc-ubuntu-cloud
lxc-altlinux  lxc-busybox    lxc-cirros  lxc-download  lxc-gentoo  lxc-opensuse      lxc-plamo   lxc-sparclinux  lxc-ubuntu
```

Creating a symlink should solve the dependency issue. Maybe a flexible way of finding the LXC path could help support more systems with different paths.

**Comment by naisanza** [comment]
After creating the symlink, another error:

```
Traceback (most recent call last):
  File "/root/lwp/lib/python3.5/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/root/lwp/lib/python3.5/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/root/lwp/lib/python3.5/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/root/lwp/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/root/lwp/lib/python3.5/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/root/lwp/lib/python3.5/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/root/lwp/lib/python3.5/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/root/lwp/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/root/lwp/lib/python3.5/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/root/lwp/lib/python3.5/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/root/LXC-Web-Panel/lwp.py", line 110, in home
    'settings': lwp.get_container_settings(container)
  File "/root/LXC-Web-Panel/lwp/__init__.py", line 301, in get_container_settings
    config.readfp(FakeSection(open(filename)))
  File "/usr/lib/python3.5/configparser.py", line 760, in readfp
    self.read_file(fp, source=filename)
  File "/usr/lib/python3.5/configparser.py", line 715, in read_file
    self._read(f, source)
  File "/usr/lib/python3.5/configparser.py", line 1089, in _read
    fpname, lineno)
configparser.DuplicateOptionError: While reading from '<???>' [line 21]: option 'lxc.group' in section 'DEFAULT' already exists
```

**Comment by naisanza** [comment]
With Python2.7 and flask==0.9

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/Flask-0.9-py2.7.egg/flask/app.py", line 1701, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/Flask-0.9-py2.7.egg/flask/app.py", line 1689, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/usr/local/lib/python2.7/dist-packages/Flask-0.9-py2.7.egg/flask/app.py", line 1687, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/Flask-0.9-py2.7.egg/flask/app.py", line 1360, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/Flask-0.9-py2.7.egg/flask/app.py", line 1358, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/Flask-0.9-py2.7.egg/flask/app.py", line 1344, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/root/LXC-Web-Panel/lwp.py", line 100, in home
    listx = lxc.listx()
  File "/root/LXC-Web-Panel/lxclite/__init__.py", line 172, in listx
    state = info(container)['state']
  File "/root/LXC-Web-Panel/lxclite/__init__.py", line 127, in info
    output=True).splitlines()
AttributeError: 'bool' object has no attribute 'splitlines'
```

**Comment by naisanza** [comment]
Last error was actually caused due to AppArmor being removed when removing all python packages, which in-turn removed LXC. Installed LXC and it works now.

Only works with python2.7, does not work with python3.5
